id: I38738B57
legacy_id: P006751
ocr_import_info:
  bdrc_scan_id: W26074
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T09:22:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:23:13.422664+00:00'
last_modified: 2022-09-02 14:23:27.399256
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W26074
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26074
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་བརྒྱུད་ཀྱི་ས་བཅད་དང་ཚིག་ལེའུར་བྱད་པའི་དེའི་འགྲེལ་པ་ལེགས་བཤད་རྒྱ་མཚོ།
  author: རྒྱུད་སྨད་ཤེས་རབ་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.7918787198752524
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I4330:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4330
      total_pages: 420
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4330.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7918787198752524
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
