id: P006751
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W26074
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་བརྒྱུད་ཀྱི་ས་བཅད་དང་ཚིག་ལེའུར་བྱད་པའི་དེའི་འགྲེལ་པ་ལེགས་བཤད་རྒྱ་མཚོ
  author: ''
  volumes:
    679b6c62a28640439516f9acf8dfb78a:
      image_group_id: I4330
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
