id: opecha:P006751
initial_creation_type: ocr
source_metadata:
  id: bdr:W26074
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་བརྒྱུད་ཀྱི་ས་བཅད་དང་ཚིག་ལེའུར་བྱད་པའི་དེའི་འགྲེལ་པ་ལེགས་བཤད་རྒྱ་མཚོ
  volume: ''
  author: ''
